### PR TITLE
Bug: Interrupt Stop:  Race fix during Interrupt. 

### PR DESCRIPTION
**Pull request by hackintoshrao**
The issue is described here https://github.com/minio/minio/issues/1617 . The proposed fix solves the issue.

### CODE REVIEW

**Comment by davecheney** [comment]
Thank you for this PR, I will review it shortly.

This may be invalid, profiling and the race detector will give unreliable results.

**Comment by davecheney** [comment]
This should be fixed by removing the ability to run the profiler twice per program execution, see 7a1e760

**Comment by hackintoshrao** [comment]
Thank you @davecheney

**Comment by davecheney** [comment]
Thanks. Please let me know if it fixes the issue. Please feel free to open
another issue if the problem persists.

**Comment by hackintoshrao** [comment]
@davecheney : This fixes the issue. Thank you.

**Pull request closed without merging**
